# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Tag IRL' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tag IRL

pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'MapKitGoogleStyler', :git => 'https://github.com/fmo91/MapKitGoogleStyler.git'

end
